folder="SavedPlots_20240814"
cp -p ${folder}/nJets.pdf Figure_002-a.pdf
cp -p ${folder}/Mass.pdf Figure_002-b.pdf
cp -p ${folder}/jetPt[0].pdf Figure_003-a.pdf
cp -p ${folder}/jetPt[1].pdf Figure_003-b.pdf
cp -p ${folder}/absjetEta[0].pdf Figure_003-c.pdf
cp -p ${folder}/absjetEta[1].pdf Figure_003-d.pdf
cp -p ${folder}/mjj.pdf Figure_004-a.pdf
cp -p ${folder}/dEtajj.pdf Figure_004-b.pdf
cp -p ${folder}/Mass0j.pdf Figure_005-a.pdf
cp -p ${folder}/Mass1j.pdf Figure_005-b.pdf
cp -p ${folder}/Mass2j.pdf Figure_005-c.pdf
cp -p ${folder}/Mass3j.pdf Figure_005-d.pdf
cp -p ${folder}/Mass4j.pdf Figure_005-e.pdf
cp -p ${folder}/MassFull.pdf Figure_006-a.pdf
cp -p ${folder}/Mass0jFull.pdf Figure_006-b.pdf
cp -p ${folder}/Mass1jFull.pdf Figure_006-c.pdf
cp -p ${folder}/Mass2jFull.pdf Figure_006-d.pdf
cp -p ${folder}/Mass3jFull.pdf Figure_006-e.pdf
cp -p ${folder}/Mass4jFull.pdf Figure_006-f.pdf
cp -p ${folder}/Ratio_MassAllj.pdf Figure_007-a.pdf
cp -p ${folder}/Ratio_nJets.pdf Figure_007-b.pdf
cp -p ${folder}/Ratio_jetPt[0].pdf Figure_008-a.pdf
cp -p ${folder}/Ratio_jetPt[1].pdf Figure_008-b.pdf
cp -p ${folder}/Ratio_absjetEta[0].pdf Figure_008-c.pdf
cp -p ${folder}/Ratio_absjetEta[1].pdf Figure_008-d.pdf
cp -p ${folder}/Ratio_dEtajj.pdf Figure_009-a.pdf
cp -p ${folder}/Ratio_mjj.pdf Figure_009-b.pdf
cp -p ${folder}/Ratio_MassFull.pdf Figure_010.pdf
cp -p ${folder}/Ratio_Mass0j.pdf Figure_011-a.pdf
cp -p ${folder}/Ratio_Mass1j.pdf Figure_011-b.pdf
cp -p ${folder}/Ratio_Mass2j.pdf Figure_011-c.pdf
cp -p ${folder}/Ratio_Mass34j.pdf Figure_011-d.pdf
cp -p ${folder}/Ratio_Mass0jFull.pdf Figure_012-a.pdf
cp -p ${folder}/Ratio_Mass1jFull.pdf Figure_012-b.pdf
cp -p ${folder}/Ratio_Mass2jFull.pdf Figure_012-c.pdf
cp -p ${folder}/Ratio_Mass34jFull.pdf Figure_012-d.pdf
